### ISSUE TITLE
template not working

### ISSUE THREAD

**Issue by sachinmahale** [nitzien/zabbix-misc#1]
Hi Nitin, 

I used this template on my zabbix server. The zabbix version is 4.0. but it is not working. 

I am receiving this alert: 

![image](https://user-images.githubusercontent.com/22630860/56434563-bb919a00-62f2-11e9-98cf-7812cc5a56ce.png)

When commandline I check perform testing, the zabbix server able to collect mysql data from agent machine:

![image](https://user-images.githubusercontent.com/22630860/56434623-01e6f900-62f3-11e9-9940-95d4bd38ea20.png)

graph is also not showing any data: 

![image](https://user-images.githubusercontent.com/22630860/56434679-29d65c80-62f3-11e9-9fb2-a71bc2adb1ac.png)

Could you please let me know what is wrong?

The zabbix agent on machine is 3.4.

**Comment by sachinmahale** [comment]
issue resolved by correcting serveractive and Hostname entry in zabbix agent config.

**Comment by flashultra** [comment]
Hi @sachinmahale 
 How you manage to fix your problem ? 

On my zabbix_agentd.conf file I have 
 `ServerActive=xxx.xxx.xxxx.  #ip of the server
 Hostname=Zabbix server
and collect some statistic but mysql template doesn't work. 
I'm using zabbix 4.2

**Comment by nitzien** [comment]
@flashultra Can you please share logs that you get in agent server? 

Is your hostname "Zabbix Server" correct? I will hope to see some mysql server unless you are monitoring your zabbix server itself.

**Comment by flashultra** [comment]
@nitzien  Thank  you! The problem was in the hostname indeed. 
Thank you again for your help.
