### ISSUE TITLE
Why use JSONPath and not regular expression?

### ISSUE THREAD

**Issue by roeezab** [nitzien/zabbix-misc#2]
Hi,
First, thanks for publishing your solution. I just implemented it today in our zabbix with a few adjustments.
One of them was to just get the query results as plain text, and then use preprocessing with regular expression instead of JSONPath.
So I wondered,  why did you choose JSONPath? Maybe because of performance considerations? Something else?

**Comment by nitzien** [comment]
Thanks. 

I felt jsonpath is more trustworthy than regular expression. There is some remote chance of something in data that one did not expect. Jsonpath will be absolute.
