### ISSUE TITLE
error: split is not defined

### ISSUE THREAD

**Issue by alkshbird** [nitzien/zabbix-misc#3]
Getting following error, Please help.

jq version 1.3

root@ip-172-30-0-232:/etc/zabbix/zabbix_agentd.d# mysql --defaults-file=/var/lib/zabbix/.my.cnf --defaults-group-suffix=_monitoring -N -e  "show global status" |   jq  -c '.  | split("\n")[:-1]  | map (split("\t") | {(.[0]) : .[1]}  ) | add  ' -R -s
error: split is not defined
.  | split("\n")[:-1]  | map (split("\t") | {(.[0]) : .[1]}  ) | add
     ^^^^^
error: split is not defined
.  | split("\n")[:-1]  | map (split("\t") | {(.[0]) : .[1]}  ) | add
                              ^^^^^
2 compile errors

**Comment by alkshbird** [comment]
This was "jq" version issue. Issue resolved as i upgrades jq from version 1.3 to 1.5

wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
chmod +x jq-linux64
sudo mv jq-linux64 $(which jq)

/etc/zabbix/zabbix_agentd.d# mysql --defaults-file=/var/lib/zabbix/.my.cnf --defaults-group-suffix=_monitoring -N -e "show global status" | jq -c '. | split("\n")[:-1] | map (split("\t") | {(.[0]) : .[1]} ) | add ' -R -s
Above command is working fine but still no data in zabbix server

**Comment by alkshbird** [comment]
made changes on client side, client file configuration is as following:-

UserParameter=mysql_server_status, mysql --defaults-file=/var/lib/zabbix/.my.cnf --defaults-group-suffix=_monitoring -N -e  "show global status" |   jq  -c '.  | split("\n")[:-1]  | map (split("\t") | {(.[0]) : .[1]}  ) | add  ' -R -s

and with above configuration "zabbix_agent -t mysql_server_status" is working fine and giving expected result. But zabbix server GUI is not showing any data. Please help.

**Comment by nitzien** [comment]
Is your zabbix configured to work as active agent? Please ensure ServerActive and Hostname is defined in zabbix agent configuration.

**Comment by magiruuvelvet** [comment]
is this template not compatible with passive checks? if so, than that's sad because the agent can't reach the server, only the server can reach the agent

EDIT: i managed to open a route to the server, it's hacky and messy, but works somehow. i'm worried about the security though

**Comment by nitzien** [comment]
Sorry for late response of this. Yes, it is only for passive check now. I will add  for active check. 

Also, I feel it is more risky to open ports on zabbix client machines which has more important application running. Opening agent port can make those applications less secure.
