### ISSUE TITLE
Can't import mysql template

### ISSUE THREAD

**Issue by ddmo** [nitzien/zabbix-misc#7]
Hi! I can't import the last version of mysql template. After select file, the browser remain in loading status... any error on error log, any messages. Anyone can help me? I've zabbix 5.4.
Thanks in advance
Stefano

**Comment by nitzien** [comment]
Hi Stefano,  

I am sorry I have not tested this on recent version of Zabbix. I will need to install and test this out. 

Could you try importing any other template and see if that works and issue is not really with Zabbix import?

Regards,
Nitin

**Comment by ddmo** [comment]
After several retries, was fine!
Thanks

Stefano
Il 9 lug 2021, 20:32 +0200, Nitin Jain ***@***.***>, ha scritto:
